2023-10-27 15:51:31 main.py [line:21] 	INFO:	<<=======================任务开始=======================>>
2023-10-27 15:51:31 main.py [line:22] 	INFO:	任务开始执行时间 2023-10-27 15:51:31.468444

2023-10-27 15:51:35 main.py [line:113] 	ERROR:	输入的路径错误或不存在
Traceback (most recent call last):
  File "D:\CocoPyRPA\PyRPA桌面自动化程序\execute\src\main.py", line 111, in <module>
    w = xlrd.open_workbook(filename)
  File "D:\ADev\Python3.10.8\lib\site-packages\xlrd\__init__.py", line 166, in open_workbook
    file_format = inspect_format(filename, file_contents)
  File "D:\ADev\Python3.10.8\lib\site-packages\xlrd\__init__.py", line 60, in inspect_format
    with open(path, "rb") as f:
OSError: [Errno 22] Invalid argument: '形如 D:/aa/bb.xls'


